### ISSUE TITLE
chaos meteor can have negative cooldown

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1032] opened 2021-04-12 02:50 UTC
![chaos meteor negative cooldown](https://user-images.githubusercontent.com/59403389/114334332-a26efd00-9b4a-11eb-86e2-4b4f72d7a7c2.jpg)

**Comment by Draze22** [comment] 2021-04-12 04:33
Duplicate of issue #1024.

**Closed by Draze22** 2021-04-12 04:33 UTC
Labels: duplicate
