### ISSUE TITLE
Time walk aghanims wont proc time lock

### ISSUE THREAD

**Issue by TheRealAdeft** [arcadia-redux/custom_hero_clash_issues#985] opened 2021-03-28 17:13 UTC
![Untitled1](https://user-images.githubusercontent.com/67648195/112760945-60fb2f80-902b-11eb-9a97-4f3bb4f7753c.png)

**Comment by Draze22** [comment] 2021-03-29 02:35
Duplicate of issue #881.

**Closed by Draze22** 2021-03-29 02:35 UTC
Labels: duplicate
