### ISSUE TITLE
Invoker's Icewall cannot be skilled

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#1003] opened 2021-04-02 10:31 UTC
![image](https://user-images.githubusercontent.com/78736351/113408100-4d601800-93e1-11eb-9d95-52df9ec890f5.png)

is there a prerequisite  before picking it? or just a bug?

**Comment by Draze22** [comment] 2021-04-15 05:19
Duplicate of issue #648.

**Closed by Draze22** 2021-04-15 05:19 UTC
Labels: duplicate
