### ISSUE TITLE
Make Soul Bind (Grimstroke) search for creeps as a secondary target

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#852] opened 2021-02-08 05:00 UTC
We made Soul Bind be able to be cast on creeps to make it more useful but never allowed it to target bind to a second creep which would make it much more useful if it could.

**Comment by SanctusAnimus** [comment] 2021-05-12 09:51
Duplicate of #513

**Closed by SanctusAnimus** 2021-05-12 09:51 UTC
Labels: enhancement
