### ISSUE TITLE
Posion Sting isn't affected by Torture Pipe

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1262] opened 2021-06-12 07:25 UTC
The tooltip is affected by Torture Pipe but the damage dealt is not.

**Comment by SanctusAnimus** [comment] 2021-06-12 07:47
![image](https://user-images.githubusercontent.com/43399078/121769307-7e8c5f80-cb6b-11eb-975c-db542f30d964.png)
it is though? original damage for reference is `6 14 22 30`. Purple numbers may be unchanged, but it's not something we can influence (and those numbers don't account for spell amp too anyway)

**Comment by SanctusAnimus** [comment] 2021-06-12 07:49
actually, even purple numbers are displaying changed value, so i don't thing how's that reproducible

**Comment by Draze22** [comment] 2021-06-12 07:50
> actually, even purple numbers are displaying changed value, so i don't thing how's that reproducible

When I tested it in game it wasn't dealing more damage. The base damage (with spell amp) was 40, torture pipe said it was increasing it to 80 damage but it still did 40 damage per tick.

**Comment by fcalife** [comment] 2021-06-12 07:51
probably ticks every 0.5 seconds

**Comment by fcalife** [comment] 2021-06-12 07:51
it doesn't

**Comment by SanctusAnimus** [comment] 2021-06-12 07:51
It deals correct damage if you account magic resistance

**Comment by Draze22** [comment] 2021-06-12 08:13
Left creep was hit with Torture Pipe affected Posion Sting, Right is without Torture Pipe, the bonus intelligence and therefore spell amp account for the difference in health.

![image](https://user-images.githubusercontent.com/63279022/121769938-bfa36480-cba9-11eb-8415-8bff4154a7fe.png)

**Comment by Snoresville** [comment] 2021-06-12 08:20
what round are you in? i'd hardly think that a difference in 12 damage and a bit of spell amp is enough to damage creeps that are hitting you enough to make you go under 50% even with that regen

**Comment by Draze22** [comment] 2021-06-12 08:21
> what round are you in? i'd hardly think that a difference in 12 damage and a bit of spell amp is enough to damage creeps that are hitting you enough to make you go under 50% even with that regen

Pretty sure it was round 11, also I didn't have those items the whole time, I bought them when I started dying.

**Comment by SanctusAnimus** [comment] 2021-06-12 08:34
Level 4 posion sting, pipe t1 and t2, left is damage incoming in damage filter, in brackets is damage special value
![image](https://user-images.githubusercontent.com/43399078/121770446-01181d80-cb72-11eb-863d-04fa432d3dd3.png)

**Comment by SanctusAnimus** [comment] 2021-06-12 08:35
So torture pipe as it is, does work, it's just poison sting for some reason doesn't account for it. It starts working correctly if poison sting is learned after torture pipe is purchased, so i guess it's just a cached variable, and needs modifier update?

**Comment by ZLOY5** [comment] 2021-06-12 08:37
Try call OnUpgrade for all abiltites when Pipe equiped

**Comment by SanctusAnimus** [comment] 2021-06-12 08:41
yeap, seems to be working that way, closing

**Closed by SanctusAnimus** 2021-06-12 08:41 UTC
Labels: bug, reproducible
