### ISSUE TITLE
Decay radius isn't shown while casting it

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#826] opened 2021-02-01 05:40 UTC
![image](https://user-images.githubusercontent.com/63279022/106419206-15555b00-64ac-11eb-97d5-fa8044819601.png)

**Comment by fcalife** [comment] 2021-02-02 03:02
Unable to reproduce in tools. Maybe this has to do with clientside utility functions only loading in tools mode?

**Comment by fcalife** [comment] 2021-02-02 04:23
Indeed, that's the case. Here's the error when playing on live servers:

[VScript] Script Runtime Error: ...ripts\vscripts\heroes\hero_undying\undying_decay_lua.lua:11: attempt to call method 'HasShard' (a nil value)

It's possible this has to do with encryption. Maybe the relevant clientside utils file is not loaded because addon_game_mode_client.lua is not encrypted properly?

**Comment by ZLOY5** [comment] 2021-02-02 09:27
Maybe we need add addon_game_init_client and utils\client_utils to clientModules list of encrypter?
https://github.com/dota2unofficial/custom_game_encrypter/blob/5b645cab50f0f219def574b7de57fc2da8b8ce9d/config.js#L19

**Comment by ZLOY5** [comment] 2021-02-02 09:32
Or you can add this files as exception, they do not contain anything important for steal

**Comment by fcalife** [comment] 2021-02-02 11:33
Added those to the encryption config, it's up to @darklordabc to implement it in the next upload

**Comment by SanctusAnimus** [comment] 2021-04-02 06:48
Reopen if still an issue, should be fixed

**Closed by SanctusAnimus** 2021-04-02 06:48 UTC
Labels: bug, niche, reproducible
