### ISSUE TITLE
Rapidly levelling Track 3 times makes it have 1 charge for that round

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1260] opened 2021-06-12 07:02 UTC
1. Pick Track **and** level it 3 times as fast as possible.
3. Tack will have only 1 charge until the next round.

**Comment by SanctusAnimus** [comment] 2021-06-12 07:41
![oyaHaEraJd](https://user-images.githubusercontent.com/43399078/121769162-bb0b8b80-cb6a-11eb-9150-ed1a5e6c592e.gif)

???

**Comment by Draze22** [comment] 2021-06-12 07:52
> ![oyaHaEraJd](https://user-images.githubusercontent.com/43399078/121769162-bb0b8b80-cb6a-11eb-9150-ed1a5e6c592e.gif)
> 
> ???

Maybe it requires rapidly picking and levelling it, I'll do some more testing.

**Comment by SanctusAnimus** [comment] 2021-06-12 07:53
i've picked it and leveled up, i've relearned into it, retrained, switched hero - works anyway

**Comment by SanctusAnimus** [comment] 2021-06-12 07:53
Until you have a stable reproduction, closed.

**Comment by Draze22** [comment] 2021-06-12 08:05
![image](https://user-images.githubusercontent.com/63279022/121769755-c087c680-cba8-11eb-9e60-b01afe8e74f0.png)

**Comment by SanctusAnimus** [comment] 2021-06-12 08:07
So what? what does this image mean? I tried all sorts of combinations plenty of times and couldn't reproduce it. Unless you have a stable reproduction (not in demo, in ffa or duos), close this

**Comment by Draze22** [comment] 2021-06-12 08:10
> So what? what does this image mean? I tried all sorts of combinations plenty of times and couldn't reproduce it. Unless you have a stable reproduction (not in demo, in ffa or duos), close this

I did it in FFA. You just have to pick track and level it to level 3 all within a second.

**Comment by SanctusAnimus** [comment] 2021-06-12 08:23
fixed

**Closed by SanctusAnimus** 2021-06-12 08:23 UTC
Labels: bug, niche, reproducible
