### ISSUE TITLE
Add an option to pick an ability later

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1114] opened 2021-04-29 07:57 UTC
Make it more or less identical to the pick innate later button.

In the event that a player has no innate selection waiting, clicking the pick ability later button would minimize the ability selection the same way the pick innate later button does.

If there is an ability/innate selection waiting when the pick ability/innate later button is clicked; the pick ability button should be positioned above the pick innate button. (The pick innate button would need to be moved down)

**Comment by AustraliaIsMyCity** [comment] 2021-05-04 09:42
This is a duplicate of https://github.com/arcadia-redux/custom_hero_clash_issues/issues/488

**Closed by AustraliaIsMyCity** 2021-05-04 09:42 UTC
Labels: enhancement, urgent
