### ISSUE TITLE
[enfos] Wrath of Nature disables enemy blink in PvE area

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1789] opened 2021-11-14 14:09 UTC
also adds "rooted" status for like 0.1 sec (too fast to screenshot),
which result in micro interruption

all that also affects enemies in 1v1 duel,
when cast from inside the PvE area by another player, not the one dueling

![Wrath of Nature disables enemy blink in PvE](https://user-images.githubusercontent.com/59403389/141684632-52cbf154-ddc4-4727-b3c8-223ab011e9c6.jpg)

**Comment by Draze22** [comment] 2021-11-15 02:34
Duplicate of #1612.

**Closed by Draze22** 2021-11-15 02:34 UTC
