### ISSUE TITLE
Text to rearrange abilities overlaps on actual abilities (maybe russian/chinese issue)

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1075] opened 2021-04-23 03:32 UTC
![image](https://user-images.githubusercontent.com/16277198/115814435-5f5d3580-a438-11eb-9531-441af450a0eb.png)

**Comment by Draze22** [comment] 2021-04-23 07:09
I've never seen this in English.

**Comment by ZLOY5** [comment] 2021-04-23 07:49
Cant reproduce this, maybe it happens only with a specific screen resolution or aspect ratio

**Comment by Draze22** [comment] 2021-06-16 10:56
No more reports of this closing for now.

**Closed by Draze22** 2021-06-16 10:56 UTC
Labels: bug
