### ISSUE TITLE
Bug Pulse nova + Arcane bolt

### ISSUE THREAD

**Issue by M1cr0be** [arcadia-redux/custom_hero_clash_issues#1309] opened 2021-06-29 22:01 UTC
Pulse nova + Arcane bolt with Aghanim's scepter shard and you crazy amount of intelligence and armor (around 100 stack). Idk if it work with mana shield or other spells with no CD

**Comment by Draze22** [comment] 2021-06-30 07:29
Duplicate of Issue #1079.

**Closed by Draze22** 2021-06-30 07:29 UTC
Labels: duplicate
