### ISSUE TITLE
Killing heroes gives experience

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#955] opened 2021-03-25 10:04 UTC
![image](https://user-images.githubusercontent.com/63279022/112455332-b924fe00-8dad-11eb-9eb7-52fc30dbcf9f.png)

**Comment by fcalife** [comment] 2021-03-26 02:07
Unable to reproduce in either ffa or duos, at multiple exp levels and with multiple level differences. Gonna close this one and call it user error.

**Closed by fcalife** 2021-03-26 02:07 UTC
Labels: bug, needs confirmation

**Comment by Osamabinfrank** [comment] 2021-03-26 02:11
I think they might talk about draw, when a draw occurs and both enemies kill each other they both gain an extra level

**Comment by fcalife** [comment] 2021-03-26 02:11
draws no longer happen
